### ISSUE TITLE
improve the login form and landing page of the student portal website

### ISSUE THREAD

**Issue by vedantmistryy** [vedantmistryy/vedantmistryy.github.io#1]
![image](https://github.com/vedantmistryy/vedantmistryy.github.io/assets/106006564/ed992183-3bc4-46ab-b4f5-1428a452fcd5)

**Comment by sb-decoder** [comment]
@vedantmistryy please Assign me  this task

**Comment by HimankPatidar** [comment]
hey, i am quite good in HTML and CSS. Can you please assign the task

**Comment by weberankit** [comment]
Hello I am already working on this issue plz assigned to me and also 80% completed

**Comment by vedantmistryy** [comment]
@weberankit go ahead, make it more interactive 
When i press enter button on my keyboard, credentials doesn't get submitted, so also fix that
And add aome better ui, np if original look is losed,
Don't change credentials

**Comment by vedantmistryy** [comment]
@weberankit i don't want registration, don't add
Contact me on discord "niklaus.one"

**Comment by vedantmistryy** [comment]
@HimankPatidar 
@sb-decoder 
You guys can work on making overall website look more better

**Comment by weberankit** [comment]
I have made all the changes plz check this 

when the user clicks on the enter button login information is submitted and the redirect link issue fixed
UI ----
login page- 
![image](https://github.com/vedantmistryy/vedantmistryy.github.io/assets/94105514/9a81517b-6c7b-4db1-abe7-f40797716cdb)
Teacher -
![image](https://github.com/vedantmistryy/vedantmistryy.github.io/assets/94105514/8317c448-aa9e-41e4-a3bc-db29f9e83468)
student
![image](https://github.com/vedantmistryy/vedantmistryy.github.io/assets/94105514/e8ca38ad-0742-4584-8e4c-42968d939623)

**Comment by Debshibraj123** [comment]
assign me this task I want to work on this

**Comment by rohitdubey1352** [comment]
Hey, @vedantmistryy I'm a frontend developer and I can suggest that, your website is not looking good for any user and I want to make some changes such as add some background color, add attractive font, small animations such as hover and make the form more professional to make more genuine for students.
Thanks

**Comment by weberankit** [comment]
@vedantmistryy  plz check pr #8

**Comment by weberankit** [comment]
> Hey, @vedantmistryy I'm a frontend developer and I can suggest that, your website is not looking good for any user and I want to make some changes such as add some background color, add attractive font, small animations such as hover and make the form more professional to make more genuine for students. Thanks

plz check another issue I have already made pr and am further working on this thank you

**Comment by vedantmistryy** [comment]
assigning everyone
