### ISSUE TITLE
Issue in navigating to other page

### ISSUE THREAD

**Issue by codermoderSD** [vedantmistryy/vedantmistryy.github.io#2]
When we click on the links in the navbar, it gives an error message saying 
<img width="446" alt="image" src="https://user-images.githubusercontent.com/67367732/193439517-860210e2-8c98-4e27-acaa-384f2e0daa27.png">

There is some issue in the index HTML file

**Comment by vedantmistryy** [comment]
you have been assigned , create a pr pls
and may be we can connect on discord my username is here: vedantmistryy#5206

**Comment by vedantmistryy** [comment]
> When we click on the links in the navbar, it gives an error message saying <img alt="image" width="446" src="https://user-images.githubusercontent.com/67367732/193439517-860210e2-8c98-4e27-acaa-384f2e0daa27.png">
> 
> There is some issue in the index HTML file

@codermoderSD had solved the issue Thankyou
