### ISSUE TITLE
improve the student dashboard

### ISSUE THREAD

**Issue by vedantmistryy** [vedantmistryy/vedantmistryy.github.io#2]
![image](https://github.com/vedantmistryy/vedantmistryy.github.io/assets/106006564/a831d37e-df2b-48fb-84c5-ea0428b3ce57)

**Comment by psykat1116** [comment]
@vedantmistryy I want to work on this. Can you please assign it to me.

**Comment by psykat1116** [comment]
Please assign me this task under hacktoberfest

**Comment by Artlfmj** [comment]
Can I work on this stuff?

**Comment by kushaljgec2025** [comment]
I want to work on this. Can you please assign it to me.

**Comment by hollermay** [comment]
Hey there @vedantmistryy, I'm Udayan, I have worked on **Dashboards** before plus I'm making one for a hackathon and also I have made a **portfolio website** you can check that in my profile or _here is the link- hollermay.github.io/Resum_e, and other projects like get-your-quote_(link-get-your-quote.pages.dev)_ and I'm 100% sure I can assist you under this and provide the best solution for you if you assign me this task :)

**Comment by vedantmistryy** [comment]
@Artlfmj 
@psykat1116 
@kushaljgec2025 
@hollermay 
Raise pr asap and attach ss of your contribution

**Comment by Artlfmj** [comment]
![image](https://github.com/vedantmistryy/vedantmistryy.github.io/assets/73163159/c3982b8e-b199-4474-823f-5cb9ce05b512)
Is this better @vedantmistryy ?

**Comment by vedantmistryy** [comment]
add some more functionalities, and i'll be using this in my real project, so create accordingly
like attendance, result, pay fees - for student

**Comment by vedantmistryy** [comment]
for teachers - link same page for adding marks (student's can't edit their marks right?), so only teacher has access to edit marks

**Comment by hollermay** [comment]
@vedantmistryy I have made changes to your student-dashboard please review it.
![Screenshot (118)](https://github.com/vedantmistryy/vedantmistryy.github.io/assets/122338009/95c1dd83-b587-46b6-ab03-2a50bcf7c579)
_
