### ISSUE TITLE
Improving footer and matching it with base theme

### ISSUE THREAD

**Issue by MR-DHRUV** [vedantmistryy/vedantmistryy.github.io#20]

**Comment by vedantmistryy** [comment]
Sure go ahead with it

**Comment by vedantmistryy** [comment]
![image](https://user-images.githubusercontent.com/106006564/193455349-3e110f85-9cc8-44f5-aa5a-1ad7a628dd32.png)
are you correcting this? @MR-DHRUV

**Comment by MR-DHRUV** [comment]
yes @vedantmistryy , I'm correcting it and making it match with theme

**Comment by vedantmistryy** [comment]
@MR-DHRUV Thank you, I don't know who had done this , carry on mate

**Comment by vedantmistryy** [comment]
#21 done by @MR-DHRUV Thanks mate

**Comment by Jaspreet099** [comment]
hey @vedantmistryy can I work on this issue because the text and everything are not aligned in footer!
