### ISSUE TITLE
admin-dashboard needs to be improvised

### ISSUE THREAD

**Issue by hollermay** [vedantmistryy/vedantmistryy.github.io#22]

**Comment by hollermay** [comment]
@vedantmistryy please review the pull request

**Comment by hollermay** [comment]
![Web capture_1-10-2023_225058_127 0 0 1](https://github.com/vedantmistryy/vedantmistryy.github.io/assets/122338009/dea946ee-ad8a-4f89-98e6-df32ed701856)

**Comment by Debshibraj123** [comment]
@vedantmistryy I can work on this please assign

**Comment by vedantmistryy** [comment]
@Debshibraj123 fix before 12 hrs am going to make repo archive
and raise new pr
