### ISSUE TITLE
Nav Links Hover Color is Different on Home Screen 

### ISSUE THREAD

**Issue by abhayst007** [vedantmistryy/vedantmistryy.github.io#24]
On Home screen the nav links color on hover is blue
![image](https://user-images.githubusercontent.com/75574622/193456661-684b2351-cb04-4694-9398-1f27ba922caf.png)
![image](https://user-images.githubusercontent.com/75574622/193456666-3e0271e1-19ba-420e-8dfe-9515f5341e84.png)

while on other screens -> about,brands,custom,contact
The Nav Links Color is Black on HOVER
![image](https://user-images.githubusercontent.com/75574622/193456725-50e7077b-7bb5-4ee8-bc8a-42110faa9709.png)
![image](https://user-images.githubusercontent.com/75574622/193456731-6b59bab5-9257-428a-837a-1555670957c1.png)

**Comment by vedantmistryy** [comment]
you can wok on it @abhayst007

**Comment by abhayst007** [comment]
for sure

**Comment by abhayst007** [comment]
Just found out that there is difference in navbar fonts between
Home and other screens

In home Screen the following is the navbar
![image](https://user-images.githubusercontent.com/75574622/193457310-5e873b7f-49ea-45a7-979b-a0a7af7301a2.png)

In other screens the navbar
![image](https://user-images.githubusercontent.com/75574622/193457329-476355a3-c152-49e6-88f5-579f2ce24211.png)
