### ISSUE TITLE
Working on the Navbar

### ISSUE THREAD

**Issue by kaur-rajdeep** [vedantmistryy/vedantmistryy.github.io#24]
I would like to work on the navbar of this project. Will be making it responsive and provide a better UI.
Could you please assign me under the hacktoberfest 2023?
Would be glad to work on it. 
Thank you.
![image](https://github.com/vedantmistryy/vedantmistryy.github.io/assets/106001705/278c8c96-6fd5-43f6-8336-4ca5075d2cec)

**Comment by vedantmistryy** [comment]
@kaur-rajdeep it would be better if you creating an overall better landing page?

**Comment by kaur-rajdeep** [comment]
Do you have any current design, how you would like it to be?

**Comment by vedantmistryy** [comment]
i don't have any make according to your will, but i should have amazing UI
don't change the form
