### ISSUE TITLE
Add Favicon to website 

### ISSUE THREAD

**Issue by chaitanyakatore** [vedantmistryy/vedantmistryy.github.io#3]
-  Adding favicon can make this website more recongnizable and identical 
-  will you please assign this issue to me so I can give best Favicon to this website according to it's context 
- I have some amazing favicon

**Comment by vedantmistryy** [comment]
@chaitanyakatore raise pr and attacj ss of your contribution

**Comment by chaitanyakatore** [comment]
will you please add label **hacktoberfest** to it

**Comment by Debshibraj123** [comment]
@vedantmistryy  please assign me this work

**Comment by AnushkJain2201** [comment]
@vedantmistryy Please Let Me Do It. And Tell Me Which Type Of Favicon Do You Want

**Comment by vedantmistryy** [comment]
@AnushkJain2201 @Debshibraj123 @chaitanyakatore join discord server https://discord.gg/c8c4MhbhbY
