### ISSUE TITLE
No SignUp option on landingpage

### ISSUE THREAD

**Issue by saurabhbakolia** [vedantmistryy/vedantmistryy.github.io#31]
# As There is not Signup option right now, in the landing page. 
![image](https://github.com/vedantmistryy/vedantmistryy.github.io/assets/78996216/887f7281-586f-467c-9e8a-d3327e7d0803)

- Some UI/UX improvement is required.

**Comment by saurabhbakolia** [comment]
Assign this feature to me. 
I want to add signup modal.

**Comment by vedantmistryy** [comment]
@saurabhbakolia not needed it is website for university

**Comment by saurabhbakolia** [comment]
> @saurabhbakolia not needed it is website for university

Then how can I contribute to it. I am not able to login to the dashboard.
