### ISSUE TITLE
Social link not working

### ISSUE THREAD

**Issue by AyushJain001** [vedantmistryy/vedantmistryy.github.io#34]
I want to work on social link responsive. Assign me under hacktoberfest tag

**Comment by vedantmistryy** [comment]
@AyushJain001 yeah u can create accounts for that with images so it look good and write in profile that it's a dummy company 
connect with me on discord vedantmistryy#5206

**Comment by abhishekpatil4** [comment]
@AyushJain001  Can I work on this? I'm a full stack developer (HTML CSS Javascript + MERN Stack - MongoDB Express Js React Js Node Js)

**Comment by vedantmistryy** [comment]
> @AyushJain001 Can I work on this? I'm a full stack developer (HTML CSS Javascript + MERN Stack - MongoDB Express Js React Js Node Js)
Hello Abhishek can you pls contact me on discord my username is : vedantmistryy#5206

**Comment by bhavyajshah** [comment]
Hello, @vedantmistryy I can do this task easily just please provide me with your social id.

Please assign me this task.

**Comment by vedantmistryy** [comment]
@bhavyajshah  hello bhavya it would be better if you contact me on discord, my username: vedantmistryy#5206

**Comment by sooraj-gk** [comment]
Fixed Social Media Links #41
