### ISSUE TITLE
Adding the Scroll Up Button

### ISSUE THREAD

**Issue by mgjain9871** [vedantmistryy/vedantmistryy.github.io#36]
There is no scroll up button on the website. Under this issue, I would be adding a scroll up button.
Please assign me this issue under Hacktoberfest.
@vedantmistryy

**Comment by vedantmistryy** [comment]
Go ahead mate @mgjain9871

**Comment by harsitagarwalla187** [comment]
Can i work in this Issue?

**Comment by vedantmistryy** [comment]
@harsitagarwalla187 sure everyone are open to work
You Connect with me on discord on vedantmistryy#5206 for coordination 
Thank you
