### ISSUE TITLE
There is no register page for student and teacher

### ISSUE THREAD

**Issue by Gobinath-B** [vedantmistryy/vedantmistryy.github.io#40]
There is no register page for student and teacher
. i planned to built a register page for student as well as teacher
. label this issue as hacktober and assign me to this issue

**Comment by vedantmistryy** [comment]
this is custom made student portal for universities and school, so credentials would be provided by respective school, so sign up/register page is not needed.
your concerns are appreciated

**Comment by Gobinath-B** [comment]
@vedantmistryy got it , thanks
