### ISSUE TITLE
Contact Us heading not Visible

### ISSUE THREAD

**Issue by mgjain9871** [vedantmistryy/vedantmistryy.github.io#59]
In the Contact Page, the contact us heading is not visible, it got hidden under the navbar.

![image](https://user-images.githubusercontent.com/71882225/193498523-de6c4c90-0ecb-4ba0-9e84-33ee0b109022.png)

Please assign me this issue under Hacktoberfest.
@vedantmistryy

**Comment by vedantmistryy** [comment]
clone the latest repo and work on it @mgjain9871 go ahead mate
