### ISSUE TITLE
[BUGS]: Image missing or Damage

### ISSUE THREAD

**Issue by rohitdubey1352** [vedantmistryy/vedantmistryy.github.io#7]
The University Logo is not showing or it damage inside of the code and it should be fix.

Assign this task to me, @vedantmistryy

**Comment by vedantmistryy** [comment]
raise pr in 10 minutes, this is very small issue

**Comment by rohitdubey1352** [comment]
Sure

**Comment by rohitdubey1352** [comment]
Should I add Non-Copyright University Logo?

**Comment by vedantmistryy** [comment]
use any random image, like harvard

**Comment by vedantmistryy** [comment]
attach ss with pull request

**Comment by rohitdubey1352** [comment]
Now, see this time I think I had made it.

**Comment by vedantmistryy** [comment]
done
